### ISSUE TITLE
Custom gradle.properties values

### ISSUE THREAD

**Issue by The-Code-Monkey** [HardNorth/github-version-generate#24]
Hi, 

Is there any way to grab a custom value out of the gradle.properties file.

e.g. if im using an external library that i want to be able to get the value of.

**Comment by HardNorth** [comment]
@The-Code-Monkey Hello, thanks for your input!

Unfortunately, I'm not really got what you wanted. Do you want to grab custom properties from `gradle.properties` and populate them as environment variables?

**Comment by The-Code-Monkey** [comment]
Yeah exactly i want to be able to grab multiple custom variables from the gradle.properties.

so i would need to be able to specify an array like structure e.g. 

```
["^version=", "^package_version="]
```

and then they would be added as env variables.

**Comment by HardNorth** [comment]
@The-Code-Monkey Hmm, that isn't something the action originally supposed to do. But I can think about the enhancement implementation.

**Comment by The-Code-Monkey** [comment]
Yeah i know its kind of a strange edge case for my current project.

**Comment by HardNorth** [comment]
Done: https://github.com/HardNorth/github-version-generate/releases/tag/v1.2.0
Documentation: https://github.com/HardNorth/github-version-generate#data-extract
