### ISSUE TITLE
Example without gradle 

### ISSUE THREAD

**Issue by Ismoh** [HardNorth/github-version-generate#29]
Hey @HardNorth,
your github action looks really promising, but I dont get, if this is useful for projects not using gradle.

I am trying to write a multiplayer mod for Noita. This is the version file I added yesterday:
https://github.com/Ismoh/NoitaMP/blob/27-rework-networkcomponents/.version

I am searching for a tool, which increase this version and I am curious if your action might help.

I used regex to see if my version string matches, but it didnt.

Is it possible to use a file with a version string and your action will increase the numbers, or am I stupid? :D

Looking forward to hearing from you.

Thanks a lot!

**Comment by HardNorth** [comment]
@Ismoh Well I'm building the action with the action and it's JavaScript: https://github.com/HardNorth/github-version-generate/blob/develop/.github/workflows/release.yml#L41-L46

**Comment by Ismoh** [comment]
Thanks for the answer! Going to have a look on this the next days! I try to get this working on my own. If I fail some hints would be awesome!
Thank you for making this action public 👍

**Comment by HardNorth** [comment]
No answer

**Comment by Ismoh** [comment]
I'll come back to this, when I am working on it:
https://github.com/Ismoh/NoitaMP/issues/42

Until then it can be stay closed. I'll reopen it, when I have issues.

Thanks a lot!

**Comment by Ismoh** [comment]
Just wants to let you know:
It's working like a charm, here is my customised approach using labels:
https://github.com/Ismoh/NoitaMP/actions/runs/2629420828/workflow#L79-L89
Thanks a lot!
