### ISSUE TITLE
Add a NEXT_RELEASE_VERSION env var

### ISSUE THREAD

**Issue by eygraber** [HardNorth/github-version-generate#34]
Would it be possible to add a `NEXT_RELEASE_VERSION` variable e.g. if `CURRENT_VERSION` is `0.0.1-SNAPSHOT` then `NEXT_RELEASE_VERSION` would be `0.0.2`.

**Comment by HardNorth** [comment]
Hmm, OK. I'll take it into account.

**Comment by HardNorth** [comment]
Done: https://github.com/HardNorth/github-version-generate/releases/tag/v1.2.0

**Comment by eygraber** [comment]
Awesome, thank you!
