### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by eygraber** [HardNorth/github-version-generate#45]
I started getting the following warning in my builds:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: HardNorth/github-version-generate@v1.3.0

**Comment by HardNorth** [comment]
@eygraber Got it, will update. Thanks for bringing this up!

**Comment by HardNorth** [comment]
@eygraber, Shoul be fixed in: https://github.com/HardNorth/github-version-generate/releases/tag/v1.4.0

**Comment by eygraber** [comment]
Thank you!
